server:
  port: 8080

spring:
  application:
    name: tt-api-gateway

  main:
    web-application-type: reactive

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${auth-server.issuer-uri}

  cloud:
    gateway:
      server:
        webflux:
          trusted-proxies: "..."
          routes:

            - id: auth-server-oauth2
              uri: ${tt.services.auth-service.uri}
              predicates:
                - Path=/oauth2/**, /login, /default-ui.css
              filters: [ ]

            - id: sas-oauth2
              uri: ${tt.services.auth-service.uri}
              predicates:
                - Path=/sas/oauth2/**
              filters:
                - RewritePath=/sas/(?<segment>.*), /${segment}

            - id: sas-auth-rest
              uri: ${tt.services.auth-service.uri}
              predicates:
                - Path=/api/v1/auth/**

            - id: sas-authorizations-admin
              uri: ${tt.services.auth-service.uri}
              predicates:
                - Path=/api/v1/authorizations/**

            - id: sas-clients-admin
              uri: ${tt.services.auth-service.uri}
              predicates:
                - Path=/api/v1/clients/**

            - id: sas-swagger
              uri: ${tt.services.auth-service.uri}
              predicates:
                - Path=/sas/swagger-ui/**, /sas/v3/api-docs/**, /sas/v3/api-docs.yaml
              filters:
                - RewritePath=/sas/(?<segment>.*), /${segment}

            - id: task-service-api
              uri: ${tt.services.task-service.uri}
              predicates:
                - Path=/api/v1/tasks/**,
                  /api/v1/task-priorities/**,
                  /api/v1/task-statuses/**,
                  /api/v1/task-types/**,
                  /api/v1/attachments/**,
                  /api/v1/comments/**,
                  /api/v1/storage/**

            - id: task-service-swagger
              uri: ${tt.services.task-service.uri}
              predicates:
                - Path=/task/swagger-ui/**,
                  /task/v3/api-docs/**,
                  /task/v3/api-docs.yaml
              filters:
                - RewritePath=/task/(?<segment>.*), /${segment}


            - id: user-service-api
              uri: ${tt.services.user-service.uri}
              predicates:
                - Path=/api/v1/users/**,
                  /api/v1/roles/**,
                  /api/v1/permissions/**

            - id: user-service-internal-api
              uri: ${tt.services.user-service.uri}
              predicates:
                - Path=/api/v1/internal/users/**

            - id: user-service-swagger
              uri: ${tt.services.user-service.uri}
              predicates:
                - Path=/user/swagger-ui/**,
                  /user/v3/api-docs/**,
                  /user/v3/api-docs.yaml
              filters:
                - RewritePath=/user/(?<segment>.*), /${segment}

          globalcors:
            add-to-simple-url-handler-mapping: true
            cors-configurations:
              '[/oauth2/token]':
                allowedOrigins: [ "http://localhost:8085", "http://localhost:8080", "null" ]
                allowedMethods: [ GET, POST, OPTIONS ]
                allowedHeaders: [ "*" ]
                allowCredentials: true
          forwarded:
            enabled: true
          x-forwarded:
            enabled: true
            for-enabled: true
            host-enabled: true
            port-enabled: true
            proto-enabled: true
            prefix-enabled: false


auth-server:
  issuer-uri: http://localhost:8080

tt:
  services:
    user-service:
      uri: http://localhost:9591
    task-service:
      uri: http://localhost:9590
    auth-service:
      uri: http://localhost:8080

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web.cors: DEBUG
    org.springframework.web.cors.reactive: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: DEBUG
    org.springframework.cloud.gateway.filter: DEBUG
    org.springframework.http.server.reactive: DEBUG
    org.springframework.security.web.server.authorization: DEBUG
    org.springframework.security.web.server.authorization.AuthorizationWebFilter: DEBUG
    ru.otus.java.springframework.yampolskiy.ttapigateway.logging.ForwardedHeadersLoggingGlobalFilter: WARN

