server:
  port: 8080

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5434/tt_oauth2_authorization_server
    username: tt_oauth2_authorization_server_admin
    password: tt_oauth2_authorization_server_admin

auth-server:
  base-uri: http://localhost:8080

user-service:
  base-uri: http://localhost:9591
  public-base-uri: http://localhost:9591

task-service:
  public-base-uri: http://localhost:9590

