server:
  port: 9590

spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://tt-task-service-postgres:5432/tt_task_service
    username: tt_task_service_admin
    password: tt_task_service_admin

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://tt-oauth2-authorization-server:8080

gateway:
  public-base-uri: http://localhost:8085

openapi:
  server-url: ${gateway.public-base-uri}
  auth-url: ${gateway.public-base-uri}

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    config-url: /task/v3/api-docs/swagger-config
    url: /task/v3/api-docs
    oauth2-redirect-url: ${gateway.public-base-uri}/task/swagger-ui/oauth2-redirect.html
